name: Clone & update

# run with cronjob every day
on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Clone datamine
        run: git clone -v --progress --depth 1 https://github.com/gszabi99/War-Thunder-Datamine.git 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  
          cache: 'pip'

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Run updator
        run: |
          python main.py
        env:
          DATAMINE_LOCATION: "./War-Thunder-Datamine"
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_PORT: ${{ secrets.DB_PORT }}
        - name: Update files
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git pull --rebase origin master
          git add locales nations assets -f
          git commit -m "Update files" || echo "No changes!"
          git push origin master
      